[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D LAB_FIRMWARE_VERSION=\"0.1.0\"
  -D LAB_DEVICE_PROFILE=\"governance-demo\"
